version: '3.3'

services:
  go-app:
    image: abhishek1805/go_app:latest
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    networks:
      - myapp-network

  nextjs-app:
    image: abhishek1805/nextjs_app:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    enviroment:
      - NODE_ENV=development
    networks:
      - myapp-network

  wordpress:
    image: abhishek1805/wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - myapp-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data: